version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    comands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    comands:
      - echo "Zipping deployment package..."  
  post_build:
    comands:
      - echo "Updating lambda Function..."
      - aws lamda update-function-code --function-name github-to-lambda-demo --zip-file fileb://deployment_package.zip
      - echo "DONE!!"